require_relative './config/environment'
require 'sinatra/activerecord/rake'

desc "Start our app console"
task :console do
  Pry.start
end
desc "gettin' it crunk"
task :percolating do
  puts "no hateration in this dancery"
end
